### ISSUE TITLE
Error While deploying in vps and pls add docker option also add payment and broadcast system

### ISSUE THREAD

**Issue by PREETCHAUHAN** [superhexa/CompressBot#1]
python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 43, in <module>
    app.run()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/run.py", line 58, in run
    self.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/connect.py", line 46, in connect
    await self.session.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 109, in start
    await self._send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 334, in _send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.

![012](https://github.com/user-attachments/assets/cd559658-03b7-48da-8b13-932c35aafc7c)

**Comment by superhexa** [comment]
I'll have it fixed ASAP. No need for the payment or broadcast system bcz this project is just a base for a specific function, not a full bot (:

**Comment by PREETCHAUHAN** [comment]
> I'll have it fixed ASAP. No need for the payment or broadcast system bcz this project is just a base for a specific function, not a full bot (:

ok
